kind: Pod
apiVersion: v1
metadata:
  name: demo-app
  labels:
    app: demo-app
  namespace: metallb-demo-app
spec:
  containers:
    - name: demo-app
      image: hashicorp/http-echo
      args:
        - "-text=MetalLB Demo application right here"
        - "-listen=:8080"
