kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple
    application: shard-1
  namespace: metallb-demo-app
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple"
        - "-listen=:8080"
