kind: Service
apiVersion: v1
metadata:
  name: demo-app-service
  namespace: metallb-demo-app
spec:
  selector:
    app: demo-app
  ports:
    - port: 8080
  type: LoadBalancer
# Code IP address for fixed or allow metallb to allocate dynamically
#  externalIPs:
#  - 10.100.59.201
